# Generated by Django 2.1 on 2018-08-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=40)),
                ('LIKE', models.IntegerField()),
                ('CONTEXT', models.TextField()),
                ('UPLOADER', models.CharField(max_length=40)),
                ('PHOTO', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SoolGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=40)),
                ('LIKE', models.IntegerField()),
                ('CONTEXT', models.TextField()),
                ('UPLOADER', models.CharField(max_length=40)),
                ('PHOTO', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_ID', models.CharField(max_length=40)),
                ('USER_PW', models.CharField(max_length=20)),
                ('USER_NAME', models.CharField(max_length=40)),
            ],
        ),
    ]
