# Generated by Django 2.1 on 2018-09-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soolapp', '0002_tip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
